---
title: "week06"
---

텍스트의 치환
sub()
gsub()


```{r}
txt <- "Data Analytics is useful. Data Analytics is also interesting"
sub(pattern = "Data",replacement="Business",x=txt)
gsub(pattern = "Data",replacement="Business",x=txt)
gsub(pattern = "Data",replacement=" ",x=txt)
```
```{r}
text2 <- c("product.csv","order.csv","customer.csv")#확장자필요없다
gsub(".csv","",text2) #이름만나옴
```

<br>
정규표현식

```{r}
words <- c("at","bat","cat","chaenomeloes","chase","cheep","check","cheese","chick","hat")
```

```{r}
# grep(pattern, 가져오고자 하는 데이터셋, value값)
grep("che", words, value = TRUE) # words벡터에서 "che"를 포함하고 있는 문자열을 가져와라
```

```{r}
grep("a", words, value = TRUE) # "a"문자열이 포함된 문자열을 가져와라
```


```{r}
grep("at", words, value = TRUE)
```
```{r}
# 정규표현식으로 표현
grep("[ch]", words, value = TRUE) #c혹은 h가 포함된 모든 문자열을 가져와라
```
```{r}
grep("[at]", words, value = TRUE) # "at" vs "[at]" : a 혹은 t가 들어간 문자열 모두 추출
```

```{r}
grep("ch|at", words, value = TRUE) # ch 혹은 at 가 들어간 문자열 추출
```
```{r}
grep("che|at", words, value = TRUE) #che혹은 at가 포함된 문자열
```

```{r}
# ch로 시작, ck로 끝나는데 가운데 문자열이 e 혹은 i
grep("ch[e|i]ck", words, value=TRUE)
```
<br>
수량자 - 문자열에서 반복되는 것
<br>수량자 바로 앞에 붙은 문자열이 반복되는 횟수를 수량자를 통해 지정
<br>? : 앞 문자는 없거나(0회) 또는 1회 출현(최대 1회)
<br>* : 앞 문자는 0회이상 반복됨(최소0회)
<br>+ : 앞 문자는 1회 이상 반복됨(최소1회)
<br>{n} : 앞문자는 정확히 n회 반복됨
<br>{n,} : 앞문자는 n회이상 반복됨
<br>{n,m} : 앞문자는 n회이상, m회이하 반복됨(n~m회)
```{r}
grep("chas?e", words, value = TRUE) #cha 다음에, s가 0회 혹은 1번, e로 끝나는 문자열을 포함
```

```{r}
grep("chas*e", words, value = TRUE) # cha 다음에, s가 0회이상반복, e로 끝나는 문자열을 포함 

```
```{r}
grep("chas+e", words, value = TRUE) # cha다음에, s가 한 번 이상, e로 끝나는 문자열 포함
```
```{r}
words <- c("at","bat","cat","chaenomeloes","chase","cheep","check","cheese","chick","hat", "chasse")
 # chasse 추가
```


```{r}
grep("chas?e", words, value = TRUE) # cha 다음에, s가 0회 혹은 1번, e로 끝나는 문자열을 포함
```


```{r}
grep("chas*e", words, value = TRUE) # cha다음에, s가 한 번 이상, e로 끝나는 문자열 포함
```
```{r}
grep("chas+e", words, value = TRUE) # cha 다음에, s가 1회이상, e로끝나는 문자열 포함
```


```{r}
grep("ch(a*|e*)se", words, value = TRUE) #ch로 시작, se로 끝남, a가 0회이상반복 또는 e가 0회이상반복(두 가지 조건 중 하나만 만족해도 참)
```
<br>메타문자
<br>^ : 시작
<br>$ : 끝

```{r}
grep("^c", words, value = TRUE) # c로 시작하는 문자
```


```{r}
grep("t$", words, value = TRUE) # t로 끝나는 문자
```

```{r}
grep("^c.t$", words, value = TRUE) # c로 시작하고, 가운데는 모든 문자열, t로 끝나는 문자열 # . : 모든 문자열
```


```{r}
grep("^c.*t$", words, value = TRUE) # c로시작, 0회 반복 문자열, t로끝남
```

```{r}
words <- c("at","bat","cat","chaenomeloes","chase","cheep","check","cheese","chick","hat", "chasse", "ca-t") # ca-t 추가

```




```{r}
grep("^c.*t$", words, value = TRUE)
```


```{r}
grep("^[ch]?at", words, value = TRUE) # c 또는 h로 시작하는데 이것은 0회 또는 1회 반복, at로 끝남
```

<br>
문자클래스
<br>[:digit:] : 숫자
<br>[:lower:] : 알파벳소문자
<br>[:upper:] : 알파벳대문자
<br>[:alpha:] : 알파벳문자
<br>[:alnum:] : 알파벳문자+숫자
<br>[:punct:] : 문장부호
<br>[:blank:] : 블랭크문자(스페이스, 탭)
<br>[:space:] : 스페이스문자(스페이스,탭,새라인,폼피드,캐리지리턴)
<br>[:print:] : 프린트 가능 문자(알파벳문자,숫자,문장부포,스페이스문자)
<br>[:graph:] : 그래프문자(사람이 읽을 수 있는 문자:숫자,문장부호)

```{r}
words2 <- c("12 Dec","OK","http://","<TITLE>Time?<TITLE>","12345","Hi there")
words2
```


```{r}
grep("[[:alnum:]]", words2, value = TRUE) # 알파벳문자+숫자
```

```{r}
grep("[[:alpha:]]", words2, value = TRUE) # 알파벳만
```


```{r}
grep("[[:digit:]]", words2, value = TRUE)  # 숫자
```


```{r}
grep("[[:punct:]]", words2, value = TRUE) # 문장부호
```

```{r}
grep("[[:space:]]", words2, value = TRUE) 
```
<br>문자클래스시퀀스<br>백슬래시 두개사용
```{r}
grep("\\w+", words, value = TRUE) # \w : 단어, 문자.  + : 최소1회반복
```
```{r}
grep("\\s+", words, value = TRUE) # \s : space를포함한
```
```{r}
grep("\\d+", words, value = TRUE) #\d:숫자
```

```{r}
grep("\\D+", words, value = TRUE) # \D : 숫자제외문자 
```